- name: Build Docker Image and Deploy to Kubernetes
  hosts: localhost
  connection: local

  vars:
    image_name: abhi2404/my-webapp
    app_path: /mnt/c/Users/hp/Documents/NewDoc/3rd project/app
    k8s_path: /mnt/c/Users/hp/Documents/NewDoc/3rd project/k8s
    dockerhub_username: abhi2404
    dockerhub_password: "{{ lookup('env', 'DOCKER_HUB_PASS') }}"  # Secure

  tasks:

    - name: Login to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Build and Push Docker Image
      docker_image:
        name: my-webapp
        repository: "{{ image_name }}"
        tag: latest
        build:
          path: "{{ app_path }}"
        source: build
        push: yes

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f "{{ k8s_path }}/deployment.yaml"

    - name: Apply Kubernetes Service
      command: kubectl apply -f "{{ k8s_path }}/service.yml"

